spring:
  application:
    name: vanthucac
  profiles:
    active: dev
  threads:
    virtual:
      enabled: true
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

app:
  commission:
    rate: 0.05