spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vanthucac?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration: 900
  google-books:
    api-key: ${GOOGLE_BOOKS_API_KEY}
  aws:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
    region: ap-southeast-1
    s3:
      bucket: vanthucac-dev